version: '3.8'
services:

  nestjs_mysql:
    build:
      context: ./.docker/mysql
    container_name: nestjs_mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./nestjs-db:/var/lib/mysql
      - ./.docker/mysql/mysql.cnf:/etc/mysql/mysql.cnf
    networks:
      - nestjs
#Docker Networks
networks:
  nestjs:
    driver: bridge
